VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = 'robin/freebsd-10'
  config.vm.network 'private_network', type: 'dhcp'
  # Use NFS as a shared folder
  config.vm.synced_folder '.', '/vagrant', :nfs => true, id: 'vagrant-root'
  config.vm.provision 'shell', inline: 'sudo pkg install -y python ansible'
  config.vm.provision 'ansible' do |ansible|
    ansible.playbook = '../vagrant.yml'
    ansible.sudo = true
  end
end
