---
# tasks file for route53-ansible-role

- apt: name={{ item }} state=latest
  with_items:
  - python3
  - python3-setuptools

- shell: easy_install3 pip

- copy: src=requirements.txt dest=/tmp/requirements.txt

- pip: executable=/usr/local/bin/pip3 requirements=/tmp/requirements.txt

- copy: src=dns.py dest=/tmp/dns.py owner=root mode=0550
