---
# tasks file for route53-ansible-role

- apt: name={{ item }} state=latest
  with_items:
  - python3
  - python3-setuptools

- shell: easy_install3 pip

- copy: src=requirements.txt dest=/root/requirements.txt

- pip: executable=pip3 requirements=/root/requirements.txt

- copy: src=dns.py dest=/root/dns.py owner=root mode=0550
