---
# tasks file for route53-ansible-role

- include: 'Ubuntu.yml'
  when: ansible_distribution == 'Ubuntu'

- include: 'FreeBSD.yml'
  when: ansible_distribution == 'FreeBSD'

- pip: executable=/usr/local/bin/pip3 name={{ item }} state=latest
  with_items: python3_pip_packages
